### ISSUE TITLE
pip install not working?

### ISSUE THREAD

**Issue by Gerardwx** [scottcwang/openssh_key_parser#4]
Using python3.8 on Ubuntu20 I'm getting a different private_key_list.py file than in the repo. (It doesn't have the static generate method).
[private_key_list.txt](https://github.com/scottcwang/openssh_key_parser/files/8533657/private_key_list.txt)

**Comment by scottcwang** [comment]
Thanks for using! The generate method you refer to was added in 0.0.4. Unfortunately, 0.0.3 and onwards require 3.10 because I used a 3.10-specific function; so your 3.8 pip is therefore pulling 0.0.2. I do apologise for that.

**Comment by Gerardwx** [comment]
I missed the 3.10 requirement list in the release notes. Thanks for the clarification.
